### ISSUE TITLE
What provers (proof search) use this Coq_Serapy Env/Gym?

### ISSUE THREAD

**Issue by brando90** [HazardousPeach/coq_serapy#2]
Is this the Coq Env that @HazardousPeach:

1. Proverbot9001 uses?
2. Diva uses?
3. Passport uses?

Thanks in advance and thanks for sharing your code! :) 

useful general discussions, related links/discussions:
- https://github.com/princeton-vl/CoqGym/discussions/70
- https://github.com/princeton-vl/CoqGym/discussions/71
- https://github.com/HazardousPeach/coq_serapy/issues/2
- https://github.com/UCSD-PL/proverbot9001/issues/26
- https://github.com/princeton-vl/CoqGym/discussions/74
- https://coq.discourse.group/t/machine-learning-and-hammers-for-coq/303/37
- https://github.com/UCSD-PL/proverbot9001/issues/27

**Comment by brando90** [comment]
feel this is related to this (Can Proverbot9001 use PyCoq?): https://github.com/UCSD-PL/proverbot9001/issues/26

**Comment by HazardousPeach** [comment]
This is the package that Proverbot9001 uses, but not Diva or Passport. Diva and Passport are built using the CoqGym framework, for historical reasons.
